version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: job-matching-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: rootpassword 
    volumes:
      - mongo-data:/data/db 
volumes:
  mongo-data:
